post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end

use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'

target 'MKCommureApp_Example' do
  pod 'CommureGateway', :git => 'git@120.27.8.241:Commure-Tag_AC347/Commure-MK110_AC347_IOS.git', :branch => 'main'
  pod 'CommureGWThree', :git => 'git@120.27.8.241:Commure-Tag_AC347/Commure-Tag_AC347_GW_iOS.git', :branch => 'main'
end
